# Generated by Django 4.2.2 on 2024-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_chessgame_timecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='timeControl',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
