# Generated by Django 4.2.2 on 2024-04-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_chessgame_timecontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
